version: 1
policy:
  pullRequests: public
tasks:
  $let:
    head_rev:
      $if: tasks_for == "github-pull-request"
      then: ${event.pull_request.head.sha}
      else: ${event.after}
    repository:
      $if: tasks_for == "github-pull-request"
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}
    should_run:
      $match:
        (tasks_for == "github-push") || (tasks_for == "github-pull-request" && event["action"] in ["opened","reopened","synchronize"]):
  in:
    $if: should_run
    then:
      - metadata:
          name: Decision task
          description: ''
          owner: ${event.sender.login}@users.noreply.github.com
          source: ${event.repository.url}
        taskQueueId: test/linux
        deadline:
          $fromNow: 1 day
        scopes:
          - "assume:repo:github.com/Eijebong/lang-sma:branch:main"
        payload:
          maxRunTime: 3600
          # https://github.com/servo/taskcluster-bootstrap-docker-images#decision-task
          # TODO: Change this? It looks ok for our usage but we don't want to depend on servo for any change
          image: "servobrowser/taskcluster-bootstrap:decision-task@\
              sha256:7471a998e4462638c8d3e2cf0b4a99c9a5c8ca9f2ec0ae01cc069473b35cde10"
          features:
            # Needed for the decision task to create other tasks
            taskclusterProxy: true
          artifacts:
            public/repo.bundle:
              type: file
              path: /repo.bundle
              expires: {$fromNow: '1 day'}
          command:
            - /bin/bash
            - '--login'
            - '-e'
            - '-c'
            - >-
              git init repo &&
              cd repo &&
              git fetch --depth 1 "$GIT_URL" "$GIT_REF" &&
              git reset --hard "$GIT_SHA" &&
              python3 ci/decision_task.py
          env:
            GIT_URL: ${event.repository.clone_url}
            TASK_FOR: ${tasks_for}
            GIT_REF: ${event.ref}
            GIT_SHA: ${event.after}
            TASK_OWNER: ${event.pusher.name}@users.noreply.github.com
            TASK_SOURCE: ${event.compare}
