version: 1
policy:
  pullRequests: public
tasks:
  $let:
    head_rev:
      $if: tasks_for == "github-pull-request"
      then: ${event.pull_request.head.sha}
      else: ${event.after}
    repository:
      $if: tasks_for == "github-pull-request"
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}
    repo_name:
      $if: tasks_for == "github-pull-request"
      then: ${event.pull_request.parent.name}
      else: ${event.repository.name}
    should_run:
      $match:
        (tasks_for == "github-push") || (tasks_for == "github-pull-request" && event["action"] in ["opened","reopened","synchronize"]):
  in:
    $if: should_run
    then:
      - metadata:
          name: Decision task
          description: ''
          owner: ${event.sender.login}@users.noreply.github.com
          source: ${event.repository.url}
        taskQueueId: test/linux
        deadline:
          $fromNow: 1 day
        scopes:
          - "assume:repo:github.com/Eijebong/lang-sma:branch:main"
        payload:
          maxRunTime: 3600
          # TODO: Change this to a set tag and push dockerfile
          image: "registry.gitlab.com/bastien.orivel.tc/divvun-ci-docker:latest"
          features:
            # Needed for the decision task to create other tasks
            taskclusterProxy: true
          artifacts:
            public/repo.bundle:
              type: file
              path: /repo.bundle
              expires: {$fromNow: '1 day'}
          command:
            - /bin/bash
            - '--login'
            - '-e'
            - '-c'
            - >-
              git init repo &&
              cd repo &&
              git fetch --depth 1 "$GIT_URL" "$GIT_REF" &&
              git reset --hard "$GIT_SHA" &&
              python3 ci/decision_task.py
          env:
            GIT_URL: ${event.repository.clone_url}
            TASK_FOR: ${tasks_for}
            GIT_REF: ${event.ref}
            GIT_SHA: ${event.after}
            TASK_OWNER: ${event.pusher.name}@users.noreply.github.com
            TASK_SOURCE: ${event.compare}
            REPO_NAME: ${repo_name}
